x-common-env: &common-env
  TZ: ${TZ:-Asia/Shanghai}
  SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-local}
  PF4J_PLUGINS_DIR: /plugins
  YUDAO_DEMO: ${YUDAO_DEMO:-false}
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_URL: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-ruoyi-vue-pro}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_USERNAME: ${MYSQL_USERNAME:-root}
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_MASTER_PASSWORD: ${MYSQL_PASSWORD:-123456}
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SLAVE_URL: jdbc:mysql://${MYSQL_SLAVE_HOST:-${MYSQL_HOST}}:${MYSQL_SLAVE_PORT:-${MYSQL_PORT:-3306}}/${MYSQL_DATABASE:-ruoyi-vue-pro}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SLAVE_USERNAME: ${MYSQL_SLAVE_USERNAME:-${MYSQL_USERNAME:-root}}
  SPRING_DATASOURCE_DYNAMIC_DATASOURCE_SLAVE_PASSWORD: ${MYSQL_SLAVE_PASSWORD:-${MYSQL_PASSWORD:-123456}}
  SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
  SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
  SPRING_DATA_REDIS_DATABASE: ${REDIS_DATABASE:-0}
  SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
  SPRING_CLOUD_NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR:-host.docker.internal:8848}
  SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: ${NACOS_SERVER_ADDR:-host.docker.internal:8848}
  SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: ${NACOS_NAMESPACE:-dev}
  SPRING_CLOUD_NACOS_CONFIG_NAMESPACE: ${NACOS_NAMESPACE:-dev}
  SPRING_CLOUD_NACOS_DISCOVERY_GROUP: ${NACOS_GROUP:-DEFAULT_GROUP}
  SPRING_CLOUD_NACOS_CONFIG_GROUP: ${NACOS_GROUP:-DEFAULT_GROUP}
  SPRING_CLOUD_NACOS_USERNAME: ${NACOS_USERNAME:-}
  SPRING_CLOUD_NACOS_PASSWORD: ${NACOS_PASSWORD:-}
  XXL_JOB_ENABLED: ${XXL_JOB_ENABLED:-false}
  XXL_JOB_ADMIN_ADDRESSES: ${XXL_JOB_ADMIN_ADDRESSES:-http://host.docker.internal:9090/xxl-job-admin}
  XXL_JOB_ACCESS_TOKEN: ${XXL_JOB_ACCESS_TOKEN:-${XXL_JOB_ACCESSTOKEN:-default_token}}
  SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST:-host.docker.internal}
  SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
  SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
  SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-host.docker.internal:9092}
  ROCKETMQ_NAME_SERVER: ${ROCKETMQ_NAME_SERVER:-host.docker.internal:9876}

x-java-service: &java-service
  restart: always
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  gateway-server:
    <<: *java-service
    image: ${IMAGE_REPO_PREFIX:-gone-cloud}/yudao-gateway:${IMAGE_TAG:-latest}
    container_name: gone-cloud-gateway-server
    environment:
      <<: *common-env
      JAVA_OPTS: "${JAVA_OPTS_GATEWAY_SERVER:--Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom}"
    ports:
      - ${HOST_PORT_GATEWAY_SERVER:-48080}:48080
    volumes:
      - ./logs/gateway-server:/root/logs

  system-server:
    <<: *java-service
    image: ${IMAGE_REPO_PREFIX:-gone-cloud}/yudao-module-system-server:${IMAGE_TAG:-latest}
    container_name: gone-cloud-system-server
    environment:
      <<: *common-env
      JAVA_OPTS: "${JAVA_OPTS_SYSTEM_SERVER:--Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom}"
#    ports:
#      - ${HOST_PORT_SYSTEM_SERVER:-48081}:48081
    volumes:
      - ./logs/system-server:/root/logs

  infra-server:
    <<: *java-service
    image: ${IMAGE_REPO_PREFIX:-gone-cloud}/yudao-module-infra-server:${IMAGE_TAG:-latest}
    container_name: gone-cloud-infra-server
    environment:
      <<: *common-env
      JAVA_OPTS: "${JAVA_OPTS_INFRA_SERVER:--Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom}"
#    ports:
#      - ${HOST_PORT_INFRA_SERVER:-48082}:48082
    volumes:
      - ./logs/infra-server:/root/logs

  devops-server:
    <<: *java-service
    image: ${IMAGE_REPO_PREFIX:-gone-cloud}/yudao-module-devops-server:${IMAGE_TAG:-latest}
    container_name: gone-cloud-devops-server
    environment:
      <<: *common-env
      JAVA_OPTS: "${JAVA_OPTS_DEVOPS_SERVER:--Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom}"
#    ports:
#      - ${HOST_PORT_DEVOPS_SERVER:-48094}:48094
    volumes:
      - ./logs/devops-server:/root/logs

  project-server:
    <<: *java-service
    image: ${IMAGE_REPO_PREFIX:-gone-cloud}/yudao-module-project-server:${IMAGE_TAG:-latest}
    container_name: gone-cloud-project-server
    environment:
      <<: *common-env
      JAVA_OPTS: "${JAVA_OPTS_PROJECT_SERVER:--Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom}"
#    ports:
#      - ${HOST_PORT_PROJECT_SERVER:-48095}:48095
    volumes:
      - ./logs/project-server:/root/logs
