-- DevOps dictionary bootstrap data.
-- Source schema: sql/mysql/devops.sql
--
-- Notes:
-- 1. This file intentionally uses plain INSERT statements for quick manual import.
-- 2. IDs are omitted and should be generated by MySQL AUTO_INCREMENT.
-- 3. Existing common dictionaries can be reused:
--    - status columns with "0 开启 1 关闭": common_status
--    - bit(1) yes/no columns: infra_boolean_string when a UI dictionary is needed

-- ----------------------------
-- Dict types
-- ----------------------------
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 代码库提供方类型', 'dev_repo_provider_type', 0, 'DevOps 应用表 repo_provider_type', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 代码源认证类型', 'dev_repo_provider_auth_type', 0, 'DevOps 代码源表 auth_type', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 变更状态', 'dev_change_status', 0, 'DevOps 变更表 status：0 有效 1 已发布 2 废弃', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 环境阶段', 'dev_env_stage', 0, 'DevOps 环境表 env_stage：DEV TEST PRE PROD', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 基础设施类型', 'dev_infra_type', 0, 'DevOps 环境表 infra_type：K8S HOST', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 变更环境挂载状态', 'dev_change_env_mount_status', 0, 'DevOps 变更环境关系表 mount_status', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 合并状态', 'dev_pipeline_merge_status', 0, 'DevOps 变更环境关系表 last_merge_status', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 流水线阶段状态', 'dev_pipeline_stage_status', 0, 'DevOps 构建/测试/部署状态', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 审批状态', 'dev_approval_status', 0, 'DevOps 审批状态', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 流水线定义版本状态', 'dev_pipeline_definition_version_status', 0, 'DevOps 流水线定义版本状态', '1', NOW(), '1', NOW(), b'0', NULL);
INSERT INTO `system_dict_type` (`name`, `type`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `deleted_time`) VALUES ('DevOps 流水线运行状态', 'dev_pipeline_run_status', 0, 'DevOps 流水线运行状态', '1', NOW(), '1', NOW(), b'0', NULL);

-- ----------------------------
-- Dict data: dev_repo_provider_type
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (10, 'GitLab', 'GITLAB', 'dev_repo_provider_type', 0, 'primary', '', 'GitLab 代码库', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (20, 'GitHub', 'GITHUB', 'dev_repo_provider_type', 0, 'default', '', 'GitHub 代码库', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (30, 'Gitee', 'GITEE', 'dev_repo_provider_type', 0, 'danger', '', 'Gitee 代码库', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_repo_provider_auth_type
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (10, 'Access Token', 'ACCESS_TOKEN', 'dev_repo_provider_auth_type', 0, 'primary', '', 'Access Token 认证', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_change_status
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '有效', '0', 'dev_change_status', 0, 'success', '', '变更有效', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '已发布', '1', 'dev_change_status', 0, 'primary', '', '变更已发布', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '废弃', '2', 'dev_change_status', 0, 'danger', '', '变更已废弃', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_env_stage
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (10, '开发', 'DEV', 'dev_env_stage', 0, 'primary', '', '开发环境', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (20, '测试', 'TEST', 'dev_env_stage', 0, 'warning', '', '测试环境', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (30, '预发', 'PRE', 'dev_env_stage', 0, 'info', '', '预发环境', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (40, '生产', 'PROD', 'dev_env_stage', 0, 'danger', '', '生产环境', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_infra_type
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (10, 'Kubernetes', 'K8S', 'dev_infra_type', 0, 'primary', '', 'Kubernetes 集群', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (20, '主机', 'HOST', 'dev_infra_type', 0, 'info', '', '主机部署', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_change_env_mount_status
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '已挂载', '0', 'dev_change_env_mount_status', 0, 'success', '', '已挂载到环境', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '已移除', '1', 'dev_change_env_mount_status', 0, 'info', '', '已从环境移除', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '自动清理', '2', 'dev_change_env_mount_status', 0, 'warning', '', '自动清理移除', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_pipeline_merge_status
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '待处理', '0', 'dev_pipeline_merge_status', 0, 'default', '', '待处理', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '成功', '1', 'dev_pipeline_merge_status', 0, 'success', '', '合并成功', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '失败', '2', 'dev_pipeline_merge_status', 0, 'danger', '', '合并失败', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (3, '冲突', '3', 'dev_pipeline_merge_status', 0, 'warning', '', '合并冲突', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_pipeline_stage_status
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '待处理', '0', 'dev_pipeline_stage_status', 0, 'default', '', '待处理', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '运行中', '1', 'dev_pipeline_stage_status', 0, 'primary', '', '运行中', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '成功', '2', 'dev_pipeline_stage_status', 0, 'success', '', '执行成功', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (3, '失败', '3', 'dev_pipeline_stage_status', 0, 'danger', '', '执行失败', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (4, '已取消', '4', 'dev_pipeline_stage_status', 0, 'warning', '', '已取消', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_approval_status
-- ----------------------------
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '无需审批', '0', 'dev_approval_status', 0, 'default', '', '无需审批', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '待审批', '1', 'dev_approval_status', 0, 'warning', '', '待审批', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '已通过', '2', 'dev_approval_status', 0, 'success', '', '审批已通过', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (3, '已拒绝', '3', 'dev_approval_status', 0, 'danger', '', '审批已拒绝', '1', NOW(), '1', NOW(), b'0');

-- Dict data: dev_pipeline_definition_version_status
DELETE FROM `system_dict_data` WHERE `dict_type` = 'dev_pipeline_definition_version_status';
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '草稿', '0', 'dev_pipeline_definition_version_status', 0, 'info', '', '草稿版本', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '已发布', '1', 'dev_pipeline_definition_version_status', 0, 'success', '', '已发布版本', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '已归档', '2', 'dev_pipeline_definition_version_status', 0, 'default', '', '已归档版本', '1', NOW(), '1', NOW(), b'0');

-- ----------------------------
-- Dict data: dev_pipeline_run_status
-- ----------------------------
DELETE FROM `system_dict_data` WHERE `dict_type` = 'dev_pipeline_run_status';
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (0, '排队中', '0', 'dev_pipeline_run_status', 0, 'default', '', '排队中', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (1, '运行中', '1', 'dev_pipeline_run_status', 0, 'primary', '', '运行中', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (2, '成功', '2', 'dev_pipeline_run_status', 0, 'success', '', '执行成功', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (3, '失败', '3', 'dev_pipeline_run_status', 0, 'danger', '', '执行失败', '1', NOW(), '1', NOW(), b'0');
INSERT INTO `system_dict_data` (`sort`, `label`, `value`, `dict_type`, `status`, `color_type`, `css_class`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES (4, '已取消', '4', 'dev_pipeline_run_status', 0, 'warning', '', '已取消', '1', NOW(), '1', NOW(), b'0');
