-- DevOps schema draft
-- 当前已沉淀：代码源、应用、变更、环境、应用环境关系

DROP TABLE IF EXISTS `devops_repository_provider`;
CREATE TABLE `devops_repository_provider` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '代码源编号',
  `name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码源名称',
  `provider_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提供方类型（GITLAB）',
  `server_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码托管平台地址',
  `api_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'API 地址',
  `auth_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '认证类型（ACCESS_TOKEN）',
  `access_token` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '访问令牌，加密存储',
  `token_mask` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '令牌掩码',
  `scopes` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '授权范围',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `last_check_time` datetime DEFAULT NULL COMMENT '最近检测时间',
  `last_check_status` tinyint DEFAULT NULL COMMENT '最近检测状态（0 成功 1 失败）',
  `last_check_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最近检测结果',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_name` (`tenant_id`, `name`) USING BTREE,
  KEY `idx_tenant_provider_type` (`tenant_id`, `provider_type`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE,
  KEY `idx_tenant_last_check_status` (`tenant_id`, `last_check_status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 代码源表';

DROP TABLE IF EXISTS `dev_application`;
CREATE TABLE `dev_application` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用编号',
  `app_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '应用标识',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '应用名称',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '应用描述',
  `icon` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '应用图标',
  `repo_provider_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库提供方类型',
  `repo_identifier` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库唯一标识',
  `repo_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库地址',
  `default_branch_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'master' COMMENT '默认主干分支',
  `owner_user_id` bigint NOT NULL COMMENT '负责人用户编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_key` (`tenant_id`, `app_key`) USING BTREE,
  UNIQUE KEY `uk_tenant_repo_identifier` (`tenant_id`, `repo_identifier`) USING BTREE,
  KEY `idx_tenant_owner_user_id` (`tenant_id`, `owner_user_id`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 应用表';

DROP TABLE IF EXISTS `dev_change`;
CREATE TABLE `dev_change` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '变更编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `change_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更标识',
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更标题',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '变更描述',
  `branch_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更分支名称',
  `source_base_branch_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'master' COMMENT '来源基线分支名称',
  `owner_user_id` bigint NOT NULL COMMENT '负责人用户编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 有效 1 已发布 2 废弃）',
  `latest_commit_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最新提交 SHA',
  `latest_commit_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最新提交信息',
  `latest_commit_at` datetime DEFAULT NULL COMMENT '最新提交时间',
  `released_at` datetime DEFAULT NULL COMMENT '发布时间',
  `merged_to_master_at` datetime DEFAULT NULL COMMENT '合并回主干时间',
  `discarded_at` datetime DEFAULT NULL COMMENT '废弃时间',
  `discard_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '废弃原因',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_change_key` (`tenant_id`, `app_id`, `change_key`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_branch_name` (`tenant_id`, `app_id`, `branch_name`) USING BTREE,
  KEY `idx_tenant_app_status` (`tenant_id`, `app_id`, `status`) USING BTREE,
  KEY `idx_tenant_app_owner_user_id` (`tenant_id`, `app_id`, `owner_user_id`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 变更表';

DROP TABLE IF EXISTS `dev_environment`;
CREATE TABLE `dev_environment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '环境编号',
  `env_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境标识',
  `env_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境名称',
  `env_stage` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境阶段（TEST PRE PROD DEV）',
  `infra_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '基础设施类型（K8S HOST）',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '环境描述',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_env_key` (`tenant_id`, `env_key`) USING BTREE,
  KEY `idx_tenant_env_stage` (`tenant_id`, `env_stage`) USING BTREE,
  KEY `idx_tenant_infra_type` (`tenant_id`, `infra_type`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 环境表';

DROP TABLE IF EXISTS `dev_application_env`;
CREATE TABLE `dev_application_env` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用环境关系编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `env_id` bigint NOT NULL COMMENT '环境编号',
  `display_order` int NOT NULL DEFAULT 0 COMMENT '显示顺序',
  `deploy_branch_name_pattern` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部署分支名称模式',
  `pipeline_definition_id` bigint DEFAULT NULL COMMENT '流水线定义编号',
  `approval_required` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否需要审批',
  `approval_config_json` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审批配置 JSON',
  `current_snapshot_id` bigint DEFAULT NULL COMMENT '当前快照编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_env` (`tenant_id`, `app_id`, `env_id`) USING BTREE,
  KEY `idx_tenant_env_id` (`tenant_id`, `env_id`) USING BTREE,
  KEY `idx_tenant_pipeline_definition_id` (`tenant_id`, `pipeline_definition_id`) USING BTREE,
  KEY `idx_tenant_current_snapshot_id` (`tenant_id`, `current_snapshot_id`) USING BTREE,
  KEY `idx_tenant_app_display_order` (`tenant_id`, `app_id`, `display_order`) USING BTREE,
  KEY `idx_tenant_app_status` (`tenant_id`, `app_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 应用环境关系表';

DROP TABLE IF EXISTS `dev_change_env`;
CREATE TABLE `dev_change_env` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '变更环境关系编号',
  `change_id` bigint NOT NULL COMMENT '变更编号',
  `application_env_id` bigint NOT NULL COMMENT '应用环境关系编号',
  `mount_status` tinyint NOT NULL DEFAULT 0 COMMENT '挂载状态（0 已挂载 1 已移除 2 自动清理）',
  `mounted_at` datetime DEFAULT NULL COMMENT '挂载时间',
  `mounted_by` bigint DEFAULT NULL COMMENT '挂载人用户编号',
  `unmounted_at` datetime DEFAULT NULL COMMENT '移除时间',
  `unmounted_by` bigint DEFAULT NULL COMMENT '移除人用户编号',
  `unmounted_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '移除原因',
  `last_pipeline_run_id` bigint DEFAULT NULL COMMENT '最近一次流水线运行编号',
  `last_snapshot_id` bigint DEFAULT NULL COMMENT '最近一次环境快照编号',
  `last_merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近合并状态（0 待处理 1 成功 2 失败 3 冲突）',
  `last_build_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近构建状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_test_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近测试状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_deploy_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近部署状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最近错误信息',
  `approval_status` tinyint NOT NULL DEFAULT 0 COMMENT '审批状态（0 无需审批 1 待审批 2 已通过 3 已拒绝）',
  `approved_at` datetime DEFAULT NULL COMMENT '审批通过时间',
  `approved_by` bigint DEFAULT NULL COMMENT '审批人用户编号',
  `included_in_current_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否包含在当前快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_change_app_env` (`tenant_id`, `change_id`, `application_env_id`) USING BTREE,
  KEY `idx_tenant_app_env_mount_status` (`tenant_id`, `application_env_id`, `mount_status`) USING BTREE,
  KEY `idx_tenant_app_env_current_snapshot` (`tenant_id`, `application_env_id`, `included_in_current_snapshot`) USING BTREE,
  KEY `idx_tenant_last_pipeline_run_id` (`tenant_id`, `last_pipeline_run_id`) USING BTREE,
  KEY `idx_tenant_last_snapshot_id` (`tenant_id`, `last_snapshot_id`) USING BTREE,
  KEY `idx_tenant_approval_status` (`tenant_id`, `approval_status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 变更环境关系表';
