-- DevOps schema draft
-- 当前已沉淀：代码源、应用、变更、环境、应用环境关系

DROP TABLE IF EXISTS `devops_repository_provider`;
CREATE TABLE `devops_repository_provider` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '代码源编号',
  `name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码源名称',
  `provider_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提供方类型（GITLAB）',
  `server_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码托管平台地址',
  `api_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'API 地址',
  `auth_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '认证类型（ACCESS_TOKEN）',
  `access_token` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '访问令牌，加密存储',
  `token_mask` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '令牌掩码',
  `scopes` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '授权范围',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `last_check_time` datetime DEFAULT NULL COMMENT '最近检测时间',
  `last_check_status` tinyint DEFAULT NULL COMMENT '最近检测状态（0 成功 1 失败）',
  `last_check_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最近检测结果',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_name` (`tenant_id`, `name`) USING BTREE,
  KEY `idx_tenant_provider_type` (`tenant_id`, `provider_type`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE,
  KEY `idx_tenant_last_check_status` (`tenant_id`, `last_check_status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 代码源表';

DROP TABLE IF EXISTS `dev_application`;
CREATE TABLE `dev_application` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用编号',
  `app_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '应用标识',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '应用名称',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '应用描述',
  `icon` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '应用图标',
  `repository_provider_id` bigint NOT NULL COMMENT '代码源编号',
  `repo_provider_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库提供方类型',
  `repo_identifier` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库唯一标识',
  `repo_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '代码库地址',
  `default_branch_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'master' COMMENT '默认主干分支',
  `owner_user_id` bigint NOT NULL COMMENT '负责人用户编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_key` (`tenant_id`, `app_key`) USING BTREE,
  UNIQUE KEY `uk_tenant_repository_repo` (`tenant_id`, `repository_provider_id`, `repo_identifier`) USING BTREE,
  KEY `idx_tenant_repository_provider_id` (`tenant_id`, `repository_provider_id`) USING BTREE,
  KEY `idx_tenant_repo_provider_type` (`tenant_id`, `repo_provider_type`) USING BTREE,
  KEY `idx_tenant_owner_user_id` (`tenant_id`, `owner_user_id`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 应用表';

DROP TABLE IF EXISTS `dev_change`;
CREATE TABLE `dev_change` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '变更编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `change_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更标识',
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更标题',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '变更描述',
  `branch_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '变更分支名称',
  `source_base_branch_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'master' COMMENT '来源基线分支名称',
  `owner_user_id` bigint NOT NULL COMMENT '负责人用户编号',
  `tester_user_id` bigint DEFAULT NULL COMMENT '测试者用户编号',
  `test_passed` tinyint NOT NULL DEFAULT 0 COMMENT '测试是否通过（0 未测试/未通过 1 已通过）',
  `test_passed_commit_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '测试通过的提交 SHA',
  `code_reviewer_user_id` bigint DEFAULT NULL COMMENT '代码审核者用户编号',
  `code_review_status` tinyint NOT NULL DEFAULT 0 COMMENT '代码审核状态（0 打开中 1 进行中 2 审核通过）',
  `code_review_passed_commit_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码审核通过的提交 SHA',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 有效 1 已发布 2 废弃）',
  `latest_commit_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最新提交 SHA',
  `latest_commit_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最新提交信息',
  `latest_commit_at` datetime DEFAULT NULL COMMENT '最新提交时间',
  `released_at` datetime DEFAULT NULL COMMENT '发布时间',
  `merged_to_master_at` datetime DEFAULT NULL COMMENT '合并回主干时间',
  `discarded_at` datetime DEFAULT NULL COMMENT '废弃时间',
  `discard_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '废弃原因',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_change_key` (`tenant_id`, `app_id`, `change_key`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_branch_name` (`tenant_id`, `app_id`, `branch_name`) USING BTREE,
  KEY `idx_tenant_app_status` (`tenant_id`, `app_id`, `status`) USING BTREE,
  KEY `idx_tenant_app_owner_user_id` (`tenant_id`, `app_id`, `owner_user_id`) USING BTREE,
  KEY `idx_tenant_app_tester_user_id` (`tenant_id`, `app_id`, `tester_user_id`) USING BTREE,
  KEY `idx_tenant_app_code_reviewer_user_id` (`tenant_id`, `app_id`, `code_reviewer_user_id`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 变更表';

DROP TABLE IF EXISTS `dev_environment`;
CREATE TABLE `dev_environment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '环境编号',
  `env_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境标识',
  `env_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境名称',
  `env_stage` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '环境阶段（TEST PRE PROD DEV）',
  `infra_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '基础设施类型（K8S HOST）',
  `infra_config` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '基础设施连接配置 JSON，加密存储',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '环境描述',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_env_key` (`tenant_id`, `env_key`) USING BTREE,
  KEY `idx_tenant_env_stage` (`tenant_id`, `env_stage`) USING BTREE,
  KEY `idx_tenant_infra_type` (`tenant_id`, `infra_type`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 环境表';

DROP TABLE IF EXISTS `dev_environment_host`;
CREATE TABLE `dev_environment_host` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主机编号',
  `env_id` bigint NOT NULL COMMENT '环境编号',
  `host_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主机标识',
  `host_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主机名称',
  `host` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SSH 主机地址',
  `port` int NOT NULL DEFAULT 22 COMMENT 'SSH 端口',
  `username` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SSH 用户名',
  `auth_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '认证方式（PASSWORD PRIVATE_KEY）',
  `password` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SSH 密码，加密存储',
  `private_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SSH 私钥，加密存储',
  `passphrase` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SSH 私钥口令，加密存储',
  `sudo_enabled` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否启用 sudo',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主机描述',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `last_check_status` tinyint DEFAULT NULL COMMENT '最近检测状态（0 成功 1 失败）',
  `last_check_time` datetime DEFAULT NULL COMMENT '最近检测时间',
  `last_check_message` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最近检测消息',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_env_host_key` (`tenant_id`, `env_id`, `host_key`) USING BTREE,
  KEY `idx_tenant_env_id` (`tenant_id`, `env_id`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 环境主机表';

DROP TABLE IF EXISTS `dev_application_env`;
CREATE TABLE `dev_application_env` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '应用环境关系编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `env_id` bigint NOT NULL COMMENT '环境编号',
  `display_order` int NOT NULL DEFAULT 0 COMMENT '显示顺序',
  `pipeline_definition_id` bigint DEFAULT NULL COMMENT '流水线定义编号',
  `current_snapshot_id` bigint DEFAULT NULL COMMENT '当前快照编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_app_env` (`tenant_id`, `app_id`, `env_id`) USING BTREE,
  KEY `idx_tenant_env_id` (`tenant_id`, `env_id`) USING BTREE,
  KEY `idx_tenant_pipeline_definition_id` (`tenant_id`, `pipeline_definition_id`) USING BTREE,
  KEY `idx_tenant_current_snapshot_id` (`tenant_id`, `current_snapshot_id`) USING BTREE,
  KEY `idx_tenant_app_display_order` (`tenant_id`, `app_id`, `display_order`) USING BTREE,
  KEY `idx_tenant_app_status` (`tenant_id`, `app_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 应用环境关系表';

DROP TABLE IF EXISTS `dev_change_env`;
CREATE TABLE `dev_change_env` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '变更环境关系编号',
  `change_id` bigint NOT NULL COMMENT '变更编号',
  `application_env_id` bigint NOT NULL COMMENT '应用环境关系编号',
  `mount_status` tinyint NOT NULL DEFAULT 0 COMMENT '挂载状态（0 已挂载 1 已移除 2 自动清理）',
  `mounted_at` datetime DEFAULT NULL COMMENT '挂载时间',
  `mounted_by` bigint DEFAULT NULL COMMENT '挂载人用户编号',
  `unmounted_at` datetime DEFAULT NULL COMMENT '移除时间',
  `unmounted_by` bigint DEFAULT NULL COMMENT '移除人用户编号',
  `unmounted_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '移除原因',
  `last_pipeline_run_id` bigint DEFAULT NULL COMMENT '最近一次流水线运行编号',
  `last_snapshot_id` bigint DEFAULT NULL COMMENT '最近一次环境快照编号',
  `last_merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近合并状态（0 待处理 1 成功 2 失败 3 冲突）',
  `last_build_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近构建状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_test_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近测试状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_deploy_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近部署状态（0 待处理 1 运行中 2 成功 3 失败 4 已取消）',
  `last_error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最近错误信息',
  `approval_status` tinyint NOT NULL DEFAULT 0 COMMENT '审批状态（0 无需审批 1 待审批 2 已通过 3 已拒绝）',
  `approved_at` datetime DEFAULT NULL COMMENT '审批通过时间',
  `approved_by` bigint DEFAULT NULL COMMENT '审批人用户编号',
  `included_in_current_snapshot` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否包含在当前快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_change_app_env` (`tenant_id`, `change_id`, `application_env_id`) USING BTREE,
  KEY `idx_tenant_app_env_mount_status` (`tenant_id`, `application_env_id`, `mount_status`) USING BTREE,
  KEY `idx_tenant_app_env_current_snapshot` (`tenant_id`, `application_env_id`, `included_in_current_snapshot`) USING BTREE,
  KEY `idx_tenant_last_pipeline_run_id` (`tenant_id`, `last_pipeline_run_id`) USING BTREE,
  KEY `idx_tenant_last_snapshot_id` (`tenant_id`, `last_snapshot_id`) USING BTREE,
  KEY `idx_tenant_approval_status` (`tenant_id`, `approval_status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 变更环境关系表';

DROP TABLE IF EXISTS `dev_pipeline_definition`;
CREATE TABLE `dev_pipeline_definition` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线定义编号',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水线名称',
  `definition_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水线标识',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `application_env_id` bigint NOT NULL COMMENT '应用环境关系编号',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `draft_version_id` bigint DEFAULT NULL COMMENT '草稿版本编号',
  `published_version_id` bigint DEFAULT NULL COMMENT '已发布版本编号',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_application_env_id` (`tenant_id`, `application_env_id`) USING BTREE,
  UNIQUE KEY `uk_tenant_definition_key` (`tenant_id`, `definition_key`) USING BTREE,
  KEY `idx_tenant_app_id` (`tenant_id`, `app_id`) USING BTREE,
  KEY `idx_tenant_published_version_id` (`tenant_id`, `published_version_id`) USING BTREE,
  KEY `idx_tenant_status` (`tenant_id`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线定义表';

DROP TABLE IF EXISTS `dev_pipeline_definition_version`;
CREATE TABLE `dev_pipeline_definition_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线定义版本编号',
  `definition_id` bigint NOT NULL COMMENT '流水线定义编号',
  `version_no` int NOT NULL COMMENT '版本号，草稿固定为 0，发布版本从 1 递增',
  `version_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '版本名称',
  `version_status` tinyint NOT NULL COMMENT '版本状态（0 草稿 1 已发布 2 已归档）',
  `diagram_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '画布 JSON',
  `spec_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水线 DSL JSON',
  `node_schema_version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1.0' COMMENT '节点 schema 版本',
  `rollback_from_version_id` bigint DEFAULT NULL COMMENT '回退来源版本编号',
  `rollback_from_version_no` int DEFAULT NULL COMMENT '回退来源版本号',
  `based_on_current_version_id` bigint DEFAULT NULL COMMENT '回退发生时的当前版本编号',
  `based_on_current_version_no` int DEFAULT NULL COMMENT '回退发生时的当前版本号',
  `rollback_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '回退原因',
  `validation_result_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '校验结果 JSON',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `published_by` bigint DEFAULT NULL COMMENT '发布人用户编号',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_definition_version` (`tenant_id`, `definition_id`, `version_no`) USING BTREE,
  KEY `idx_tenant_definition_status` (`tenant_id`, `definition_id`, `version_status`) USING BTREE,
  KEY `idx_tenant_published_by` (`tenant_id`, `published_by`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线定义版本表';

DROP TABLE IF EXISTS `dev_pipeline_run`;
CREATE TABLE `dev_pipeline_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线运行编号',
  `definition_id` bigint NOT NULL COMMENT '流水线定义编号',
  `definition_version_id` bigint NOT NULL COMMENT '流水线定义版本编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `application_env_id` bigint NOT NULL COMMENT '应用环境关系编号',
  `change_id` bigint DEFAULT NULL COMMENT '锚点变更编号；无变更发布时为空',
  `change_env_id` bigint DEFAULT NULL COMMENT '锚点变更环境关系编号；无变更发布时为空',
  `branch_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部署分支名称',
  `commit_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提交 SHA',
  `change_snapshot_json` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '本次发布变更快照 JSON，记录 changeId 和发布时 commitSha',
  `run_status` tinyint NOT NULL DEFAULT 0 COMMENT '运行状态（0 排队中 1 运行中 2 成功 3 失败 4 已取消 5 等待输入）',
  `trigger_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '触发来源',
  `trigger_user_id` bigint DEFAULT NULL COMMENT '触发人用户编号',
  `triggered_at` datetime NOT NULL COMMENT '触发时间',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `jenkins_queue_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Jenkins 队列编号',
  `jenkins_build_number` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Jenkins 构建编号',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_definition_version` (`tenant_id`, `definition_id`, `definition_version_id`) USING BTREE,
  KEY `idx_tenant_app_env_status` (`tenant_id`, `application_env_id`, `run_status`) USING BTREE,
  KEY `idx_tenant_change_env` (`tenant_id`, `change_env_id`) USING BTREE,
  KEY `idx_tenant_trigger_user_id` (`tenant_id`, `trigger_user_id`) USING BTREE,
  KEY `idx_tenant_triggered_at` (`tenant_id`, `triggered_at`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线运行表';

DROP TABLE IF EXISTS `dev_pipeline_run_job`;
CREATE TABLE `dev_pipeline_run_job` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线运行任务编号',
  `pipeline_run_id` bigint NOT NULL COMMENT '流水线运行编号',
  `stage_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '阶段编号',
  `stage_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阶段名称',
  `job_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务编号',
  `job_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务名称',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务状态（PENDING RUNNING BLOCKED SUCCESS FAILED SKIPPED CANCELED）',
  `needs_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '依赖任务编号 JSON',
  `attempt` int NOT NULL DEFAULT 1 COMMENT '执行次数',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_millis` bigint DEFAULT NULL COMMENT '执行耗时，毫秒',
  `runtime_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时类型（PLATFORM LOCAL DOCKER）',
  `executor_group` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行资源池',
  `executor_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行容器镜像',
  `runtime_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时实例编号，例如容器编号',
  `runtime_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时实例名称，例如容器名称',
  `workspace_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工作目录路径',
  `worker_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '保留字段：调度 worker 编号',
  `lease_until` datetime DEFAULT NULL COMMENT '保留字段：租约过期时间',
  `summary` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '摘要',
  `error_message` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_run_job` (`tenant_id`, `pipeline_run_id`, `job_id`) USING BTREE,
  KEY `idx_tenant_run_status` (`tenant_id`, `pipeline_run_id`, `status`) USING BTREE,
  KEY `idx_tenant_run_sort` (`tenant_id`, `pipeline_run_id`, `sort`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线运行任务表';

DROP TABLE IF EXISTS `dev_pipeline_run_log`;
CREATE TABLE `dev_pipeline_run_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线运行日志编号',
  `pipeline_run_id` bigint NOT NULL COMMENT '流水线运行编号',
  `parent_id` bigint DEFAULT NULL COMMENT '父日志编号',
  `stage_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阶段编号',
  `stage_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阶段名称',
  `job_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务编号',
  `job_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
  `step_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '步骤编号',
  `step_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '步骤类型',
  `step_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '步骤名称',
  `log_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '日志层级（NODE STEP EVENT）',
  `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态（PENDING RUNNING WAITING_INPUT SUCCESS FAILED CANCELED）',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `attempt` int NOT NULL DEFAULT 1 COMMENT '执行次数',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_millis` bigint DEFAULT NULL COMMENT '执行耗时，毫秒',
  `runtime_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时类型（PLATFORM LOCAL DOCKER）',
  `executor_group` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行资源池',
  `executor_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行容器镜像',
  `runtime_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时实例编号，例如容器编号',
  `runtime_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '运行时实例名称，例如容器名称',
  `workspace_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工作目录路径',
  `summary` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '摘要',
  `context_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '运行上下文 JSON',
  `result_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '运行结果 JSON',
  `log_file_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '完整日志文件地址',
  `log_truncated` bit(1) NOT NULL DEFAULT b'0' COMMENT '日志是否截断',
  `error_message` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_run_sort` (`tenant_id`, `pipeline_run_id`, `sort`) USING BTREE,
  KEY `idx_tenant_parent_sort` (`tenant_id`, `parent_id`, `sort`) USING BTREE,
  KEY `idx_tenant_run_step` (`tenant_id`, `pipeline_run_id`, `step_id`) USING BTREE,
  KEY `idx_tenant_run_step_status` (`tenant_id`, `pipeline_run_id`, `step_type`, `status`) USING BTREE,
  KEY `idx_tenant_run_stage_job` (`tenant_id`, `pipeline_run_id`, `stage_id`, `job_id`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线运行日志表';

DROP TABLE IF EXISTS `dev_pipeline_run_log_line`;
CREATE TABLE `dev_pipeline_run_log_line` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水线运行行级日志编号',
  `pipeline_run_id` bigint NOT NULL COMMENT '流水线运行编号',
  `run_log_id` bigint NOT NULL COMMENT '流水线运行日志编号',
  `stage_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阶段编号',
  `job_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务编号',
  `step_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '步骤编号',
  `line_no` bigint NOT NULL COMMENT '行号，同一个 run_log_id 内单调递增',
  `stream_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'stdout' COMMENT '输出流类型（stdout stderr）',
  `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '日志内容',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_log_line` (`tenant_id`, `run_log_id`, `line_no`) USING BTREE,
  KEY `idx_tenant_run_id` (`tenant_id`, `pipeline_run_id`, `id`) USING BTREE,
  KEY `idx_tenant_run_step_id` (`tenant_id`, `pipeline_run_id`, `step_id`, `id`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 流水线运行行级日志表';

DROP TABLE IF EXISTS `dev_deployment_order`;
CREATE TABLE `dev_deployment_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '部署单编号',
  `pipeline_run_id` bigint NOT NULL COMMENT '流水线运行编号',
  `pipeline_run_log_id` bigint DEFAULT NULL COMMENT '流水线运行日志编号',
  `node_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水线节点编号',
  `node_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水线节点类型',
  `definition_id` bigint DEFAULT NULL COMMENT '流水线定义编号',
  `definition_version_id` bigint DEFAULT NULL COMMENT '流水线定义版本编号',
  `app_id` bigint NOT NULL COMMENT '应用编号',
  `application_env_id` bigint NOT NULL COMMENT '应用环境关系编号',
  `environment_id` bigint NOT NULL COMMENT '环境编号',
  `infra_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '基础设施类型',
  `deploy_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部署类型',
  `deploy_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部署状态',
  `attempt` int NOT NULL DEFAULT 1 COMMENT '当前执行次数',
  `current_stage` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '当前执行阶段',
  `trigger_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '触发来源',
  `trigger_user_id` bigint DEFAULT NULL COMMENT '触发人用户编号',
  `triggered_at` datetime NOT NULL COMMENT '触发时间',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `namespace` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Kubernetes Namespace',
  `workload_kind` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '工作负载类型',
  `workload_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '工作负载名称',
  `container_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '容器名称',
  `image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '目标镜像',
  `replicas` int DEFAULT NULL COMMENT '目标副本数；为空表示保留当前副本数',
  `previous_image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上一个镜像',
  `previous_replicas` int DEFAULT NULL COMMENT '上一个副本数',
  `previous_revision` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上一个 Deployment revision',
  `target_revision` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标 Deployment revision',
  `workload_uid` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Deployment UID',
  `workload_generation` bigint DEFAULT NULL COMMENT 'Deployment generation',
  `config_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '部署配置快照 JSON',
  `result_json` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '部署结果 JSON',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_run_node` (`tenant_id`, `pipeline_run_id`, `node_id`) USING BTREE,
  KEY `idx_tenant_app_env_status` (`tenant_id`, `application_env_id`, `deploy_status`) USING BTREE,
  KEY `idx_tenant_app_env_time` (`tenant_id`, `app_id`, `environment_id`, `triggered_at`) USING BTREE,
  KEY `idx_tenant_run_log` (`tenant_id`, `pipeline_run_log_id`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 部署单表';

DROP TABLE IF EXISTS `dev_offline_image_package`;
CREATE TABLE `dev_offline_image_package` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '离线镜像包编号',
  `pipeline_run_id` bigint NOT NULL COMMENT '流水线运行编号',
  `image_name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '镜像名称',
  `image_tag` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '镜像标签',
  `image_digest` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '镜像摘要（SHA256）',
  `architecture` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'amd64' COMMENT '目标架构',
  `oss_url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '离线包 OSS 访问地址',
  `package_size` bigint NOT NULL DEFAULT 0 COMMENT '包大小（字节）',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 打包中 1 就绪 2 失败）',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '错误信息',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_pipeline_run` (`tenant_id`, `pipeline_run_id`) USING BTREE,
  KEY `idx_tenant_image_status` (`tenant_id`, `image_name`(255), `status`) USING BTREE,
  KEY `idx_tenant_create_time` (`tenant_id`, `create_time`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 离线镜像包表';

DROP TABLE IF EXISTS `dev_build_host`;
CREATE TABLE `dev_build_host` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '构建主机编号',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主机名称',
  `type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主机类型（LOCAL SSH）',
  `host` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主机地址',
  `port` int DEFAULT NULL COMMENT 'SSH 端口',
  `username` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '登录用户名',
  `password` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'SSH 登录密码，加密存储',
  `private_key` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'SSH 私钥，加密存储',
  `passphrase` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'SSH 私钥口令，加密存储',
  `credential_ref` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台凭据存储引用 key',
  `labels` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主机标签，逗号分隔',
  `workspace_root` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '构建工作根目录',
  `max_concurrency` int NOT NULL DEFAULT 1 COMMENT '最大并发构建数',
  `enabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0 开启 1 关闭）',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_name` (`tenant_id`, `name`) USING BTREE,
  KEY `idx_tenant_type` (`tenant_id`, `type`) USING BTREE,
  KEY `idx_tenant_enabled_status` (`tenant_id`, `enabled`, `status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DevOps 构建主机表';
